# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a85c37a205f9e618b5677f3fbff6979199f43aa0211ec8f856fc74323a9834f507900adcae58363b5ae5a52b6a2fe0daf0b4cb864548d35df2a5a560323a80a

test:
  secret_key_base: 17ffb72577f41c40d3452e2787f6ec81f40a9e2fa19c7101dcd45b20283e78786c3389b8b7be6ae44b1422c96b3fd44c7fe07f762eaecdeea257c20acc13ed7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
